---
title: "Statistics internship - Centre Léon Bérard - Clustering"
date: "`r Sys.Date()`"
header-includes:
  - \usepackage{dsfont}
  - \usepackage{bbm}
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    lightbox: false
    fig_caption: yes
    fig_number: yes
    use_bookdown: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = "asis", message = FALSE, warning = FALSE)
```

```{r librairies, echo=FALSE, results="hide", message = FALSE, warning = FALSE}
library(dplyr) 
library(questionr)
library(GGally)
library(fossil)
library(likert)
library(nnet)
library(FactoMineR)
library(factoextra)
library(table1)
library(kableExtra)
```

```{r importation-base, echo=F, message=F, warning=F}
data <- read.csv2("exportQSeintinelles_réponsescomplètes.csv", sep = ",", dec = ",")
data <- data[, -c(1:10)]
data <- mutate(data, imc = weight / ((height / 100)^2), age = 2021 - year_birth)
data <- data[, -c(304:380, 303)]
data <- data[, -c(61, 86, 156, 251, 277, 52)]
data <- data[, -c(15, 16, 1, 50)]
data <- data[, -c(
  2, 4, 6, 8, 11, 13, 17, 19, 21, 23, 25, 27, 47, 52, 55, 95, 96, 111, 113, 115,
  117, 119, 121, 123, 125, 127, 148, 180, 212, 242, 267, 292)]
```

```{r supp-enfants, echo=FALSE, results="hide", message = FALSE, warning = FALSE}
data[434, 9] <- 2
```

```{r supp-femmes-abberantes, echo=F}
#which(is.na(data$stage1),arr.ind=TRUE)
#which(data$imc == max(data$imc), arr.ind = TRUE)
data <- data[-c(240,1031),]
```

```{r valeurs-manquantes, echo=F, message=F, warning=F, results="hide"}
data[, 10:15][is.na(data[, 10:15])] <- 0 
data[, 17][is.na(data[, 17])] <- 3 
data[, 18:23][is.na(data[, 18:23])] <- 5
data$godin_low_godinnum <- as.numeric(data$godin_low_godinnum)
data$godin_moderate_godinnum <- as.numeric(data$godin_moderate_godinnum)
data$godin_vigorous_godinnum <- as.numeric(data$godin_vigorous_godinnum)
data[,35:37][is.na(data[,35:37])] <- 0
data[, 152][is.na(data[,152])] <- 7
```

```{r tranche-age, echo=F, message=F, warning=F, results="hide"}
data$age_cut_4 <- ifelse(((data$age >= 18) & (data$age < 30)), "1",
  ifelse(((data$age >= 30) & (data$age < 50)), "2",
    ifelse(((data$age >= 50) & (data$age < 65)), "3",
      ifelse(data$age >= 65, "4", "0"))))
```

```{r imc-category, echo=F, message=F, warning=F, results="hide"}
data$imc_category <- ifelse(data$imc<18.5,1,
                     ifelse(data$imc>= 18.5 & (data$imc<25),2,
                            ifelse(data$imc>=25 & (data$imc<30),3,
                                   ifelse(data$imc>=30,4,0))))
```

```{r godin-code, echo=F, message=F, warning=F, results="hide"}
data$godin_low_godinnum <- as.numeric(data$godin_low_godinnum)
data$godin_moderate_godinnum <- as.numeric(data$godin_moderate_godinnum)
data$godin_vigorous_godinnum <- as.numeric(data$godin_vigorous_godinnum)
data$activity <- ifelse(((data$godin_low_godinnum*3) + (data$godin_moderate_godinnum*5) +
  (data$godin_vigorous_godinnum*9)) >=24, "1", "0")
```

```{r code-house-situation, echo=F, message=F, warning=F}
data$residence_location <- as.factor(data$residence_location)
data$residence_location_bis <- ifelse((data$residence_location == "1"), 1,
                                      ifelse((data$residence_location == "2"), 1, 
                                             ifelse((data$residence_location == "3"), 2,
                                                    ifelse(data$residence_location == '4', 2, 
                                                           ifelse(data$residence_location == '5', 3, 
                                                                  ifelse(data$residence_location == '6', 3, 
                                                                         ifelse(data$residence_location == '7', 4, 
                                                                                ifelse(data$residence_location == '8', 4, 0))))))))
```

```{r region, echo=F}
data <- mutate(data,
                  region = case_when(
                    residence_department=="01" ~ "1",
                    residence_department=="03" ~ "1", 
                    residence_department=="07" ~ "1",
                    residence_department=="15" ~ "1",
                    residence_department=="26" ~ "1", 
                    residence_department=="38" ~ "1", 
                    residence_department=="42" ~ "1", 
                    residence_department=="43" ~ "1",
                    residence_department=="63" ~ "1", 
                    residence_department=="69" ~ "1",
                    residence_department=="73" ~ "1", 
                    residence_department=="74" ~ "1",
                    residence_department=="21" ~ "2",
                    residence_department=="25" ~ "2",
                    residence_department=="39" ~ "2", 
                    residence_department=="58" ~ "2",
                    residence_department=="70" ~ "2", 
                    residence_department=="71" ~ "2",
                    residence_department=="89" ~ "2", 
                    residence_department=="90" ~ "2",
                    residence_department=="22" ~ "3", 
                    residence_department=="29" ~ "3",
                    residence_department=="35" ~ "3", 
                    residence_department=="56" ~ "3",
                    residence_department=="18" ~ "4",
                    residence_department=="28" ~ "4",
                    residence_department=="36" ~ "4",
                    residence_department=="37" ~ "4",
                    residence_department=="41" ~ "4",
                    residence_department=="45" ~ "4",
                    residence_department=="2B" ~ "5", 
                    residence_department=="08" ~ "6",
                    residence_department=="10" ~ "6",
                    residence_department=="51" ~ "6",
                    residence_department=="52" ~ "6",
                    residence_department=="54" ~ "6",
                    residence_department=="55" ~ "6",
                    residence_department=="57" ~ "6",
                    residence_department=="67" ~ "6",
                    residence_department=="68" ~ "6",
                    residence_department=="88" ~ "6",
                    residence_department=="02" ~ "7",
                    residence_department=="59" ~ "7",
                    residence_department=="60" ~ "7",
                    residence_department=="62" ~ "7",
                    residence_department=="80" ~ "7",
                    residence_department=="75" ~ "8",
                    residence_department=="77" ~ "8",
                    residence_department=="78" ~ "8", 
                    residence_department=="91" ~ "8",
                    residence_department=="92" ~ "8", 
                    residence_department=="93" ~ "8",
                    residence_department=="94" ~ "8", 
                    residence_department=="95" ~ "8",
                    residence_department=="14" ~ "9", 
                    residence_department=="27" ~ "9",
                    residence_department=="50" ~ "9", 
                    residence_department=="61" ~ "9",
                    residence_department=="76" ~ "9",
                    residence_department=="16" ~ "10",
                    residence_department=="17" ~ "10",
                    residence_department=="23" ~ "10",
                    residence_department=="24" ~ "10",
                    residence_department=="33" ~ "10",
                    residence_department=="40" ~ "10", 
                    residence_department=="47" ~ "10",
                    residence_department=="64" ~ "10",
                    residence_department=="79" ~ "10",
                    residence_department=="86" ~ "10",
                    residence_department=="87" ~ "10",
                    residence_department=="19" ~ "10",
                    residence_department=="09" ~ "11",
                    residence_department=="11" ~ "11",
                    residence_department=="12" ~ "11",
                    residence_department=="30" ~ "11",
                    residence_department=="31" ~ "11",
                    residence_department=="34" ~ "11",
                    residence_department=="46" ~ "11",
                    residence_department=="48" ~ "11",
                    residence_department=="65" ~ "11",
                    residence_department=="66" ~ "11",
                    residence_department=="81" ~ "11", 
                    residence_department=="82" ~ "11",
                    residence_department=="32" ~ "11", 
                    residence_department=="44" ~ "12",
                    residence_department=="49" ~ "12", 
                    residence_department=="53" ~ "12",
                    residence_department=="72" ~ "12",
                    residence_department=="85" ~ "12",
                    residence_department=="04" ~ "13",
                    residence_department=="05" ~ "13",
                    residence_department=="06" ~ "13",
                    residence_department=="13" ~ "13",
                    residence_department=="83" ~ "13", 
                    residence_department=="84" ~ "13",
                    residence_department=="971" ~ "14",
                    residence_department=="972" ~ "14",
                    residence_department=="973" ~ "14",
                    residence_department=="975" ~ "14",
                    TRUE ~ "0"))                                                          
```

```{r bc-status-bis, echo=F}
data$bc_status_bis <- ifelse(data$bc_status == "1", "1", 
                                      ifelse((data$bc_status == "2") & (data$stage1 =="1") &
                                               (data$breast_chemo == "2" |
                                                  data$breast_hormono == "2"|
                                                  data$breast_immuno == "2" |
                                                  data$breast_radio == "2" |
                                                  data$breast_surgery == "2" |
                                                  data$breast_target == "2"),"2", 
                                      ifelse((data$bc_status == "2") & (data$stage1 == "1") &
                                               (((data$breast_immuno == "1" |
                                                    data$breast_immuno == "3" |
                                                    data$breast_immuno == "4") &
                                                   (data$breast_hormono == "1" |
                                                      data$breast_hormono == "3" |
                                                      data$breast_hormono == "4") &
                                                   (data$breast_radio == "1"|
                                                      data$breast_radio == "3"|
                                                      data$breast_radio == "4" ) &
                                                   (data$breast_chemo == "1" |
                                                      data$breast_chemo == "3"|
                                                      data$breast_chemo == "4") &
                                                   (data$breast_surgery == "1"|
                                                      data$breast_surgery == "3"|
                                                      data$breast_surgery == "4") & 
                                                   (data$breast_target == "1"|
                                                      data$breast_target == "3"|
                                                      data$breast_target == "4"))), "3",
                                             ifelse(data$stage1 == "2", "4","0"))))
```

```{r barrier-faci-non-concerne-non-opinion,echo=F}
for (i in 1:nrow(data)){
  for (j in 213:235){
  if (data[i,j] == 6) {data[i,j] <- 3}
  }}

for (i in 1:nrow(data)){
  for (j in 237:259){
  if (data[i,j] == 6) {data[i,j] <- 3}
  }}
```

```{r rename-var, echo=F}
data <- dplyr::rename(data, "godin_vigorous"=godin_vigorous_godinnum, 
                               "godin_moderate"=godin_moderate_godinnum, 
                               "godin_low"=godin_low_godinnum, 
                               "techno_prog_tracker_no_use" = techno_p_tracker_no_use,
                               "techno_prog_tracker_no_info" = techno_p_tracker_no_info,
                               "techno_prog_tracker_no_price" = techno_p_tracker_no_price,
                               "techno_prog_tracker_no_security" = techno_p_tracker_no_security,
                               "techno_prog_tracker_no_dependancy" = techno_p_tracker_no_dependancy,
                               "techno_prog_tracker_no_reliability" = techno_p_tracker_no_reliability,
                               "techno_prog_tracker_no_wrist" = techno_p_tracker_no_wrist,
                               "techno_prog_tracker_no_allergy" = techno_p_tracker_no_allergy,
                               "techno_prog_tracker_no_opportunity" = techno_p_tracker_no_opportunity,
                               "techno_prog_tracker_no_userfriendly" = techno_p_tracker_no_userfriendly,
                               "techno_prog_tracker_no_tmtime" = techno_p_tracker_no_tmtime,
                               "techno_prog_tracker_no_malfunction" = techno_p_tracker_no_malfunction,
                               "techno_prog_tracker_no_alone" = techno_p_tracker_no_alone,
                               "techno_prog_tracker_no_active" = techno_p_tracker_no_active,
                               "techno_prog_tracker_no_interest" = techno_p_tracker_no_interest,
                               "techno_prog_tracker_no_unable" = techno_p_tracker_no_unable,
                               "techno_prog_tracker_no_other" = techno_p_tracker_no_other,
                               "techno_prog_tracker_fun_step" = techno_p_tracker_fun_step,
                               "techno_prog_tracker_fun_distance" = techno_p_tracker_fun_distance,
                               "techno_prog_tracker_fun_calorie" = techno_p_tracker_fun_calorie,
                               "techno_prog_tracker_fun_nbfloor" = techno_p_tracker_fun_nbfloor,
                               "techno_prog_tracker_fun_level" = techno_p_tracker_fun_level,
                               "techno_prog_tracker_fun_hr" = techno_p_tracker_fun_hr,
                               "techno_prog_tracker_fun_sitting" = techno_p_tracker_fun_sitting,
                               "techno_prog_tracker_fun_standing" = techno_p_tracker_fun_standing,
                               "techno_prog_tracker_fun_intensity" = techno_p_tracker_fun_intensity,
                               "techno_prog_tracker_fun_type" = techno_p_tracker_fun_type,
                               "techno_prog_tracker_fun_sleep" = techno_p_tracker_fun_sleep,
                               "techno_prog_tracker_fun_other" = techno_p_tracker_fun_other, 
                               "techno_prog_tracker_sha"=techno_p_tracker_sha)
```

```{r factor-var, echo=FALSE, results="hide", message = FALSE, warning = FALSE}
# creation du second tableau
data2 <- data

# renommer les categories
data2$activity <- factor(data2$activity,
                  levels=0:1, 
                  labels=c("Inactive", "Active"))
data2$imc_category <- factor(data2$imc_category, 
                             levels = 1:4, 
                             labels = c("Underweight", "Normal", "Overweight", "Obesity"))
data2$bc_status <- factor(data2$bc_status, 
                         levels=c(1, 2,0), 
                         labels=c("No", "Yes", "P-value"))
data2$bc_status_bis <- factor(data2$bc_status_bis, 
                              levels=c(1,2,3,4), 
                              labels=c("No BC", "Current localized BC", "Finished localized BC", 
                                       "Metastatic BC"))
data2$age_cut_4 <- factor(data2$age_cut_4,
  levels = 1:4,
  labels = c("18-30", "30-50", "50-65", "more than 65"))
data2$education <- factor(data2$education,
  levels = 1:6,
  labels = c("No diploma", "CAP-BEP", "BAC", "BAC+1-2", "BAC+3-4", "BAC+5-6"))
data2$marital_status <- factor(data2$marital_status,
  levels = 1:5,
  labels = c("Married-pacsee", "Common-law partner", "Divorced", "Widowed", "Single"))
data2$current_work2 <- factor(data2$current_work2,
  levels = 1:8,
  labels = c(
    "Employed full time", "Employed part time", "On sick leave", "Disabled", "Retired",
    "Student", "Looking for work", "Not working"))
data2$current_sociopro <- factor(data2$current_sociopro,
  levels = 1:9,
  labels = c(
    "Farmer-operator", "Craft trader-managerial nusinessman",
    "Executive-senior intellectual professional", "Intermediate Occupation|",
    "Employed", "Worker", "Retired", "No activity", "Other"))
data2$residence_location <- factor(data2$residence_location,
  levels = 1:8,
  labels = c(
    "Big city - center", "Big city – rest part", "Suburbs of big cities ", "Town/Small city ", 
    "Subdivision of towns/small cities",
    "Village – center", "Subdivision of village", "Isolated/hamlet"))
data2$residence_location_bis <- factor(data2$residence_location_bis,
  levels = 1:4,
  labels = c(
    "Big city & its suburb", "Town/small city & its subdivision", "Village & its subdivision", "Isolated/hamlet"))
data2$stage1 <- factor(data2$stage1,
  levels = 1:3, 
  labels = c("Localized", "Metastatic", "No BC"))
data2[, 18:23] <- lapply(data2[, 18:23], factor, 
                         levels = 1:5,
                         labels = c("Finished", "In progress", "No", "Don't know", "No BC"))
data2[, c(7,8,24:33,42:64,67:92,121:151,
          154:182,185:197,199:212,236,260)] <- lapply(data2[,c(7,8,24:33,42:64,67:92,121:151,
                                                               154:182,185:197,199:212,236,260)], factor, 
                                                      levels = 0:1,
                                                      labels = c("No", "Yes"))
data2$pref_info_pa <- factor(data2$pref_info_pa,
  levels = 0:2,
  labels = c("No", "Yes", "Maybe"))
data2$pref_pa_interest <- factor(data2$pref_pa_interest,
  levels = 0:2,
  labels = c("No", "Yes", "Maybe"))
data2$pref_pa_able <- factor(data2$pref_pa_able,
  levels = 0:2,
  labels = c("No", "Yes", "Maybe"))
data2$pref_pa_sup <- factor(data2$pref_pa_sup,
  levels = 1:7,
  labels = c(
    "Supervised face-to-face", "Supervised distance", "Unsupervised", 
    "Supervised face-to-face then distance",
    "Supervised face-to-face then unsupervised", "Supervised distance then unsupervised", 
    "No preference"))
data2$pref_pa_intensity <- factor(data2$pref_pa_intensity,
  levels = 1:4,
  labels = c("Low", "Moderate", "Vigorous", "No preference"))
data2$pref_pa_orga <- factor(data2$pref_pa_orga,
  levels = 1:3,
  labels = c("Flexible", "Planned", "No preference"))
data2$pref_pa_recur <- factor(data2$pref_pa_recur,
  levels = 1:3,
  labels = c("Same", "Differents", "No preference"))
data2$pref_pa_comp <- factor(data2$pref_pa_comp,
  levels = 1:4,
  labels = c("Competition", "Leisure", "Both", "No preference"))
data2$pref_pa_moment <- factor(data2$pref_pa_moment,
  levels = 1:5,
  labels = c("Morning", "Lunch", "Afternoon", "Evening", "No preference"))
data2$pref_pa_week <- factor(data2$pref_pa_week,
  levels = 1:4,
  labels = c("Week-end", "Monday-Friday", "Week", "No preference"))
data2$pref_pa_duration <- factor(data2$pref_pa_duration,
  levels = 1:4,
  labels = c("<15min", "15-30min", "30-60min", ">60min"))
data2$techno_tracker_fq <- factor(data2$techno_tracker_fq,
  levels = 1:7,
  labels = c(
    "Never", "<1day/sem", "1-2day/sem", "3-4day/sem",
    "5-6day/sem", "All the day", "No tracker"))
data2$techno_prog_tracker <- factor(data2$techno_prog_tracker,
  levels = 0:2,
  labels = c("No", "Yes", "Maybe"))
data2$techno_prog_tracker_sha <- factor(data2$techno_prog_tracker_sha,
  levels = 0:2,
  labels = c("No", "Yes", "Maybe"))
data2$techno_prog_app <- factor(data2$techno_prog_app,
  levels = 0:2,
  labels = c("No", "Yes", "Maybe"))
data2$techno_prog_web <- factor(data2$techno_prog_web,
  levels = 0:2,
  labels = c("No", "Yes", "Maybe"))
data2[, c(102:120)] <- lapply(data2[, c(102:120)], factor, 
                                                      levels = 1:5,
                                                      labels = c("Not helpful", "Not very helpful", "No opinion",
                                                                 "Somewhat helpful", "Very helpful"))
data2[, c(213:235, 237:259)] <- lapply(data2[, c(213:235, 237:259)], factor, 
                                                      levels = 1:5,
                                                      labels = c("Not at all", "Somewhat disagree", "No opinion-Not concerned",
                                                                 "Somewhat agree", "Strongly agree"))

data2[, c(9:15,100)] <- lapply(data2[, c(9:15,100)], as.factor)

data2$region <- factor(data2$region, 
                       levels=1:14, 
                       labels = c("ARA", "BFC", "Bre", "CVL", "Corse", "GE", "HDF", "IDF", "Norman", "NAqui", "Occi", 
                                  "PDL", "PACA", "DOM"))
```

```{r label-var, echo=F, message=F, warning=F, results="hide"}
Hmisc::label(data2$activity) <- "Physical activity : godin"
Hmisc::label(data2$marital_status) <- "Marital status"
Hmisc::label(data2$imc_category) <- "BMI classification"
Hmisc::label(data2$education) <- "Education level"
Hmisc::label(data2$current_work2) <- "Occupational status"
Hmisc::label(data2$current_sociopro) <- "Socio-professional category"
Hmisc::label(data2$residence_department) <- "Residence department"
Hmisc::label(data2$residence_location) <- "Residential location/area"
Hmisc::label(data2$residence_location_bis) <- "Residential location/area"
Hmisc::label(data2$greenspace) <- "Green space nearby"
Hmisc::label(data2$region) <- "Region"
Hmisc::label(data2$pregnancy) <- "Pregnant"
Hmisc::label(data2$nb_child_house) <- "Number of children at home"
Hmisc::label(data2$nb_child_house_age_012) <- "Children: 0-12 months"
Hmisc::label(data2$nb_child_house_age_14) <- "Children: 1-4 years"
Hmisc::label(data2$nb_child_house_age_510) <- "Children: 5-10 years"
Hmisc::label(data2$nb_child_house_age_1114) <- "Children: 11-14 years"
Hmisc::label(data2$nb_child_house_age_1517) <- "Children: 15-17 years"
Hmisc::label(data2$nb_child_house_age_18) <- "Children: 18 years and older"
Hmisc::label(data2$stage1) <- "Stage of disease"
Hmisc::label(data2$breast_surgery) <- "Surgery treatment"
Hmisc::label(data2$breast_chemo) <- "Chemotherapy treatment"
Hmisc::label(data2$breast_radio) <- "Radiotherapy treatment"
Hmisc::label(data2$breast_hormono) <- "Hormonotherapy treatment"
Hmisc::label(data2$breast_immuno) <- "Immunotherapy treatment"
Hmisc::label(data2$breast_target) <- "Targeted therapy"
Hmisc::label(data2$comor_heart) <- "Cardiovascular diseases"
Hmisc::label(data2$comor_neuro) <- "Neurological diseases"
Hmisc::label(data2$comor_endo) <- "Endocrine pathology"
Hmisc::label(data2$comor_respi) <- "Respiratory diseases"
Hmisc::label(data2$comor_infla) <- "Inflammatory diseases"
Hmisc::label(data2$comor_immun) <- "Autoimmune diseases"
Hmisc::label(data2$comor_muscle) <- "Musculoskeletal diseases"
Hmisc::label(data2$comor_locomotion) <- "Musculoskeletal surgery"
Hmisc::label(data2$comor_depression) <- "Psychiatric disorders"
Hmisc::label(data2$comor_other_cancer) <- "Other cancer"
Hmisc::label(data2$comor_other) <- "Other diseases"
Hmisc::label(data2$godin_vigorous) <- "High intensity AP (nb per week)"
Hmisc::label(data2$godin_moderate) <- "Moderate intensity AP (nb per week)"
Hmisc::label(data2$godin_low) <- "Low intensity AP (nb per week)"
Hmisc::label(data2$strengthening) <- "Muscle strengthening"
Hmisc::label(data2$covid_pa) <- "Covid influence on PA level"
Hmisc::label(data2$pref_info_pa) <- "Information and advice on sports practice"
Hmisc::label(data2$pref_info_pa_who_famdoc) <- "From whom: family doctor"
Hmisc::label(data2$pref_info_pa_who_onco) <- "From whom: oncologist"
Hmisc::label(data2$pref_info_pa_who_nurse) <- "From whom: nurse"
Hmisc::label(data2$pref_info_pa_who_hospcoach) <- "From whom: PA specialist in a health care facility"
Hmisc::label(data2$pref_info_pa_who_gymcoach) <- "From whom: gymcoach"
Hmisc::label(data2$pref_info_pa_who_patient) <- "From whom: patient"
Hmisc::label(data2$pref_info_pa_who_persocoach) <- "From whom: persocoach"
Hmisc::label(data2$pref_info_pa_who_physio) <- "From whom: physiotherapist"
Hmisc::label(data2$pref_info_pa_who_nopref) <- "From whom: no preference"
Hmisc::label(data2$pref_info_pa_who_other) <- "From whom: other"
Hmisc::label(data2$pref_info_pa_how_phone) <- "By what means : phone"
Hmisc::label(data2$pref_info_pa_how_sms) <- "By what means : sms"
Hmisc::label(data2$pref_info_pa_how_app) <- "By what means : mobile application"
Hmisc::label(data2$pref_info_pa_how_mail) <- "By what means : mail"
Hmisc::label(data2$pref_info_pa_how_web) <- "By what means : web"
Hmisc::label(data2$pref_info_pa_how_dvd) <- "By what means : dvd"
Hmisc::label(data2$pref_info_pa_how_video) <- "By what means : video"
Hmisc::label(data2$pref_info_pa_how_leaflet) <- "By what means : leaflet"
Hmisc::label(data2$pref_info_pa_how_online) <- "By what means : online"
Hmisc::label(data2$pref_info_pa_how_podcast) <- "By what means : podcast"
Hmisc::label(data2$pref_info_pa_how_facetoface) <- "By what means : face to face"
Hmisc::label(data2$pref_info_pa_how_group) <- "By what means : group"
Hmisc::label(data2$pref_info_pa_how_other) <- "By what means : other"
Hmisc::label(data2$pref_pa_interest) <- "PA interest adapted to the capacities"
Hmisc::label(data2$pref_pa_able) <- "PA practice adapted to abilities"
Hmisc::label(data2$pref_pa_type_walking) <- "PA type: walking"
Hmisc::label(data2$pref_pa_type_swimming) <- "PA type: swimming"
Hmisc::label(data2$pref_pa_type_gym) <- "PA type: gym"
Hmisc::label(data2$pref_pa_type_biking) <- "PA type: biking"
Hmisc::label(data2$pref_pa_type_dance) <- "PA type: dance"
Hmisc::label(data2$pref_pa_type_running) <- "PA type: running"
Hmisc::label(data2$pref_pa_type_strengthening) <- "PA type: strengthening"
Hmisc::label(data2$pref_pa_type_yoga) <- "PA type: yoga"
Hmisc::label(data2$pref_pa_type_pilates) <- "PA type: pilates"
Hmisc::label(data2$pref_pa_type_fitness) <- "PA type: fitness"
Hmisc::label(data2$pref_pa_type_racket) <- "PA type: racket"
Hmisc::label(data2$pref_pa_type_team) <- "PA type: team sports"
Hmisc::label(data2$pref_pa_type_other) <- "PA type: other"
Hmisc::label(data2$pref_pa_where_outside) <- "Where: outside"
Hmisc::label(data2$pref_pa_where_home) <- "Where: home"
Hmisc::label(data2$pref_pa_where_work) <- "Where: work"
Hmisc::label(data2$pref_pa_where_club) <- "Where: club"
Hmisc::label(data2$pref_pa_where_hospital) <- "Where: hospital"
Hmisc::label(data2$pref_pa_where_nopref) <- "Where: no preference"
Hmisc::label(data2$pref_pa_where_other) <- "Where: other"
Hmisc::label(data2$pref_pa_how_alone) <- "How: alone"
Hmisc::label(data2$pref_pa_how_peer) <- "How: in pairs - in groups"
Hmisc::label(data2$pref_pa_how_patient) <- "How: with patient"
Hmisc::label(data2$pref_pa_how_group) <- "How: group of non-patients"
Hmisc::label(data2$pref_pa_how_nopref) <- "How: no preference"
Hmisc::label(data2$pref_pa_how_other) <- "How: other"
Hmisc::label(data2$pref_pa_sup) <- "Supervision for sport practice"
Hmisc::label(data2$pref_pa_intensity) <- "Intensity of sport practice"
Hmisc::label(data2$pref_pa_orga) <- "Organization for sport practice"
Hmisc::label(data2$pref_pa_recur) <- "Type of activity for sports practice"
Hmisc::label(data2$pref_pa_comp) <- "Type of activity for sports practice"
Hmisc::label(data2$pref_pa_moment) <- "Time of day for sports practice"
Hmisc::label(data2$pref_pa_week) <- "Time of the week for sports practice"
Hmisc::label(data2$pref_pa_nbday) <- "Maximum number of days for sports practice"
Hmisc::label(data2$pref_pa_duration) <- "Time in minutes per session"
Hmisc::label(data2$pref_pa_strategy_gp_online) <- "Group courses via live internet with a professional"
Hmisc::label(data2$pref_pa_strategy_indiv_online) <- "Individual lessons via live internet with a professional"
Hmisc::label(data2$pref_pa_strategy_online) <- "Courses put on the internet by a professional"
Hmisc::label(data2$pref_pa_strategy_competition) <- "Gaming type competition"
Hmisc::label(data2$pref_pa_strategy_phone) <- "Telephone calls by a professional"
Hmisc::label(data2$pref_pa_strategy_sms) <- "SMS of encouragement"
Hmisc::label(data2$pref_pa_strategy_mail) <- "Encouraging e-mails"
Hmisc::label(data2$pref_pa_strategy_leaflet) <- "PA recommendations and benefits brochure"
Hmisc::label(data2$pref_pa_strategy_video) <- "Video testimonials"
Hmisc::label(data2$pref_pa_strategy_socialnet) <- "Motivation via social networks"
Hmisc::label(data2$pref_pa_strategy_tracker) <- "Use of connected watch-pedometer"
Hmisc::label(data2$pref_pa_strategy_app) <- "Application to note the exercises performed"
Hmisc::label(data2$pref_pa_strategy_notebook) <- "Notebook to record the exercises carried out"
Hmisc::label(data2$pref_pa_strategy_web) <- "Web page to note the exercises performed"
Hmisc::label(data2$pref_pa_strategy_share_entourage) <- "Share information with those around you"
Hmisc::label(data2$pref_pa_strategy_share_doctor) <- "Share information with your doctor"
Hmisc::label(data2$pref_pa_strategy_doc) <- "Online document with exercises"
Hmisc::label(data2$pref_pa_strategy_usb) <- "USB flash drive with exercises to do independently"
Hmisc::label(data2$pref_pa_strategy_dvd) <- "DVD with exercises to do autonomously"
Hmisc::label(data2$covid_pref_pa) <- "Covid impact on PA preferences"
Hmisc::label(data2$techno_socialnetwork_fb) <- "Use of facebook"
Hmisc::label(data2$techno_socialnetwork_instagram) <- "Use of instagram"
Hmisc::label(data2$techno_socialnetwork_linkedin) <- "Use of linkedin"
Hmisc::label(data2$techno_socialnetwork_twitter) <- "Use of twitter"
Hmisc::label(data2$techno_socialnetwork_no) <- "No social network"
Hmisc::label(data2$techno_socialnetwork_other) <- "Use of other social network"
Hmisc::label(data2$techno_app_fizzup) <- "Use of fizzup app"
Hmisc::label(data2$techno_app_nike) <- "Use of nike app "
Hmisc::label(data2$techno_app_adidas) <- "Use of adidas app"
Hmisc::label(data2$techno_app_strava) <- "Use of strava app"
Hmisc::label(data2$techno_app_fitbit) <- "Use of fitbit app"
Hmisc::label(data2$techno_app_garmin) <- "Use of garmin app"
Hmisc::label(data2$techno_app_jawbone) <- "Use of jawbone app"
Hmisc::label(data2$techno_app_withings) <- "Use of withings app"
Hmisc::label(data2$techno_app_xiaomi) <- "Use of xiaomi app"
Hmisc::label(data2$techno_app_healthapp) <- "Use of healthapp"
Hmisc::label(data2$techno_app_runtastic) <- "Use of runtastic app"
Hmisc::label(data2$techno_app_no) <- "No app used"
Hmisc::label(data2$techno_app_other) <- "Use of other app"
Hmisc::label(data2$techno_tracker_smartphone_podo) <- "Use of smartphone pedometer PA tracker"
Hmisc::label(data2$techno_tracker_podo) <- "Use of classic pedometer PA tracker"
Hmisc::label(data2$techno_tracker_fitbit) <- "Use of fitbit PA tracker"
Hmisc::label(data2$techno_tracker_jawbone) <- "Use of jawbone PA tracker"
Hmisc::label(data2$techno_tracker_apple) <- "Use of apple PA tracker"
Hmisc::label(data2$techno_tracker_galaxy) <- "Use of galaxy PA tracker"
Hmisc::label(data2$techno_tracker_garmin) <- "Use of garmin PA tracker"
Hmisc::label(data2$techno_tracker_xiaomi) <- "Use of xiaomi PA tracker"
Hmisc::label(data2$techno_tracker_withings) <- "Use of withings PA tracker"
Hmisc::label(data2$techno_tracker_no) <- "No PA tracker uwed"
Hmisc::label(data2$techno_tracker_other) <- "Use of other PA tracker"
Hmisc::label(data2$techno_tracker_fq) <- "Frequency of wearing the activity tracker"
Hmisc::label(data2$techno_prog_tracker) <- "Participation in a remote program via a tracker"
Hmisc::label(data2$techno_prog_tracker_no_use) <- "Why no interest: fear of use"
Hmisc::label(data2$techno_prog_tracker_no_info) <- "Why no interest: little info"
Hmisc::label(data2$techno_prog_tracker_no_price) <- "Why no interest: too expensive"
Hmisc::label(data2$techno_prog_tracker_no_security) <- "Why no interest: misuse of data"
Hmisc::label(data2$techno_prog_tracker_no_dependancy) <- "Why no interest: dependancy"
Hmisc::label(data2$techno_prog_tracker_no_reliability) <- "Why no interest: no reliability"
Hmisc::label(data2$techno_prog_tracker_no_wrist) <- "Why no interest: no wrist wear"
Hmisc::label(data2$techno_prog_tracker_no_allergy) <- "Why no interest: wrist allergy"
Hmisc::label(data2$techno_prog_tracker_no_opportunity) <- "Why no interest: no opportunity"
Hmisc::label(data2$techno_prog_tracker_no_userfriendly) <- "Why no interest: no userfriendly"
Hmisc::label(data2$techno_prog_tracker_no_tmtime) <- "Why no interest: no time"
Hmisc::label(data2$techno_prog_tracker_no_malfunction) <- "Why no interest: malfunction"
Hmisc::label(data2$techno_prog_tracker_no_alone) <- "Why no interest: no program alone"
Hmisc::label(data2$techno_prog_tracker_no_active) <- "Why no interest: too much active"
Hmisc::label(data2$techno_prog_tracker_no_interest) <- "Why no interest: no interest to practise more"
Hmisc::label(data2$techno_prog_tracker_no_unable) <- "Why no interest: physically unable"
Hmisc::label(data2$techno_prog_tracker_no_other) <- "Why no interest: other"
Hmisc::label(data2$techno_prog_tracker_fun_step) <- "Tracker info: step"
Hmisc::label(data2$techno_prog_tracker_fun_distance) <- "Tracker info: distance"
Hmisc::label(data2$techno_prog_tracker_fun_calorie) <- "Tracker info: calorie"
Hmisc::label(data2$techno_prog_tracker_fun_nbfloor) <- "Tracker info: number of floors"
Hmisc::label(data2$techno_prog_tracker_fun_level) <- "Tracker info: PA level"
Hmisc::label(data2$techno_prog_tracker_fun_hr) <- "Tracker info: heart rate"
Hmisc::label(data2$techno_prog_tracker_fun_sitting) <- "Tracker info: time spent sitting"
Hmisc::label(data2$techno_prog_tracker_fun_standing) <- "Tracker info: time spent standing"
Hmisc::label(data2$techno_prog_tracker_fun_intensity) <- "Tracker info: intensity"
Hmisc::label(data2$techno_prog_tracker_fun_type) <- "Tracker info: time spent in activities"
Hmisc::label(data2$techno_prog_tracker_fun_sleep) <- "Tracker info: time spent sleep"
Hmisc::label(data2$techno_prog_tracker_fun_other) <- "Tracker info: other"
Hmisc::label(data2$techno_prog_tracker_sha) <- "Sharing data with caregivers"
Hmisc::label(data2$techno_prog_app) <- "Participation in a remote program via an application"
Hmisc::label(data2$techno_prog_app_no_use) <- "Why no interest: fear of use"
Hmisc::label(data2$techno_prog_app_no_info) <- "Why no interest: little info"
Hmisc::label(data2$techno_prog_app_no_security) <- "Why no interest: misuse of data"
Hmisc::label(data2$techno_prog_app_no_dependency) <- "Why no interest: dependency"
Hmisc::label(data2$techno_prog_app_no_opportunity) <- "Why no interest: no opportunity"
Hmisc::label(data2$techno_prog_app_no_userfriendly) <- "Why no interest: no userfriendly"
Hmisc::label(data2$techno_prog_app_no_tmtime) <- "Why no interest: no time"
Hmisc::label(data2$techno_prog_app_no_malfunction) <- "Why no interest: malfunction"
Hmisc::label(data2$techno_prog_app_no_alone) <- "Why no interest: no program alone"
Hmisc::label(data2$techno_prog_app_no_active) <- "Why no interest: too much active"
Hmisc::label(data2$techno_prog_app_no_interest) <- "Why no interest: no interest to practise more"
Hmisc::label(data2$techno_prog_app_no_unable) <- "Why no interest: physically unable"
Hmisc::label(data2$techno_prog_app_no_other) <- "Why no interest: other"
Hmisc::label(data2$techno_prog_web) <- "Participation in a remote program via a website"
Hmisc::label(data2$techno_prog_web_no_use) <- "Why no interest: fear of use"
Hmisc::label(data2$techno_prog_web_no_info) <- "Why no interest: little info"
Hmisc::label(data2$techno_prog_web_no_security) <- "Why no interest: misuse of data"
Hmisc::label(data2$techno_prog_web_no_dependency) <- "Why no interest: dependency"
Hmisc::label(data2$techno_prog_web_no_opportunity) <- "Why no interest: no opportunity"
Hmisc::label(data2$techno_prog_web_no_userfriendly) <- "Why no interest: no userfriendly"
Hmisc::label(data2$techno_prog_web_no_tmtime) <- "Why no interest: no time"
Hmisc::label(data2$techno_prog_web_no_malfunction) <- "Why no interest: malfunction"
Hmisc::label(data2$techno_prog_web_no_alone) <- "Why no interest: no program alone"
Hmisc::label(data2$techno_prog_web_no_active) <- "Why no interest: too much active"
Hmisc::label(data2$techno_prog_web_no_interest) <- "Why no interest: no interest to practise more"
Hmisc::label(data2$techno_prog_web_no_unable) <- "Why no interest: physically unable"
Hmisc::label(data2$techno_prog_web_no_other) <- "Why no interest: other"
Hmisc::label(data2$covid_techno) <- "Covid impact on the use of technologies related to PA?"
Hmisc::label(data2$barrier_pa_fatigue) <- "Barrier: Too tired"
Hmisc::label(data2$barrier_pa_weather) <- "Barrier: Bad weather to practice"
Hmisc::label(data2$barrier_pa_pain) <- "Barrier: Severe pain"
Hmisc::label(data2$barrier_pa_partner) <- "Barrier: No partner to practice"
Hmisc::label(data2$barrier_pa_schedule) <- "Barrier: Schedule"
Hmisc::label(data2$barrier_pa_pleasure) <- "Barrier: No pleasure to practice"
Hmisc::label(data2$barrier_pa_structure) <- "Barrier: No structure around"
Hmisc::label(data2$barrier_pa_look) <- "Barrier: Fear of view of others"
Hmisc::label(data2$barrier_pa_interest) <- "Barrier: No interest"
Hmisc::label(data2$barrier_pa_family) <- "Barrier: Family commitments"
Hmisc::label(data2$barrier_pa_ignorance) <- "Barrier: Ignorance of practice"
Hmisc::label(data2$barrier_pa_price) <- "Barrier: Too expensive"
Hmisc::label(data2$barrier_pa_injury) <- "Barrier: Fear of injury"
Hmisc::label(data2$barrier_pa_social) <- "Barrier: Prefer to see friends"
Hmisc::label(data2$barrier_pa_motivation) <- "Barrier: No motivation"
Hmisc::label(data2$barrier_pa_sequelae) <- "Barrier: Significant side effects"
Hmisc::label(data2$barrier_pa_transport) <- "Barrier: No transport"
Hmisc::label(data2$barrier_pa_organisation) <- "Barrier: No organisation"
Hmisc::label(data2$barrier_pa_work) <- "Barrier: Work obligations"
Hmisc::label(data2$barrier_pa_unable) <- "Barrier: Unable"
Hmisc::label(data2$barrier_pa_insecurity) <- "Barrier: Fear of insecurity"
Hmisc::label(data2$barrier_pa_priority) <- "Barrier: Not my priority"
Hmisc::label(data2$barrier_pa_other) <- "Other barrier"
Hmisc::label(data2$covid_barrier) <- "Covid impact on your barriers to practicing PA?"
Hmisc::label(data2$facilitator_pa_control) <- "Facilitator: health control"
Hmisc::label(data2$facilitator_pa_doctor) <- "Facilitator: doctor recommandation"
Hmisc::label(data2$facilitator_pa_capacity) <- "Facilitator: improve capacity"
Hmisc::label(data2$facilitator_pa_etime) <- "Facilitator: time to devote"
Hmisc::label(data2$facilitator_pa_symptom) <- "Facilitator: improve symptom"
Hmisc::label(data2$facilitator_pa_goal) <- "Facilitator: set a goal"
Hmisc::label(data2$facilitator_pa_qol) <- "Facilitator: improve quality of live"
Hmisc::label(data2$facilitator_pa_friend) <- "Facilitator: meet friends"
Hmisc::label(data2$facilitator_pa_sleep) <- "Facilitator: improve sleep"
Hmisc::label(data2$facilitator_pa_structure) <- "Facilitator: adapted structure"
Hmisc::label(data2$facilitator_pa_fatigue) <- "Facilitator: decrease fatigue"
Hmisc::label(data2$facilitator_pa_group) <- "Facilitator: group encouragement"
Hmisc::label(data2$facilitator_pa_weight) <- "Facilitator: weight control"
Hmisc::label(data2$facilitator_pa_security) <- "Facilitator: secure environment"
Hmisc::label(data2$facilitator_pa_feeling) <- "Facilitator: better in his body"
Hmisc::label(data2$facilitator_pa_supervision) <- "Facilitator: supervision by a professional"
Hmisc::label(data2$facilitator_pa_proud) <- "Facilitator: proud of oneself"
Hmisc::label(data2$facilitator_pa_immunity) <- "Facilitator: stimulate my immune system"
Hmisc::label(data2$facilitator_pa_pleasure) <- "Facilitator: feel pleasure "
Hmisc::label(data2$facilitator_pa_competent) <- "Facilitator: feel competent"
Hmisc::label(data2$facilitator_pa_planning) <- "Facilitator: organizing my schedule"
Hmisc::label(data2$facilitator_pa_energy) <- "Facilitator: regain energy"
Hmisc::label(data2$facilitator_pa_other) <- "Facilitator: other"
Hmisc::label(data2$covid_facilitator) <- "Impact covid on the factors that facilitate your PA practice?"
Hmisc::label(data2$age) <- "Age of participants"
Hmisc::label(data2$age_cut_4) <- "Age range of participants"
Hmisc::label(data2$imc_category) <- "BMI of participants"
Hmisc::label(data2$imc) <- "BMI of participants"
```

```{r data2-supp-var, echo=F}
data2 <- data2[, -c(10:15,34:40,51,64,79,86,121,127,132,140,145,151,170,182,197,211,212,235,236,
                    259,260,6)]
data2 <- data2[, c(229,230,228,231,232,1:5,234,233,6:9,235,10:227)]
```

```{r nombre-comor, echo=F}
data$comor_nb <- rowSums(data[, 25:34])
data2$comor_nb <- data$comor_nb
data2$comor_nb <- as.numeric(data2$comor_nb)
Hmisc::label(data2$comor_nb) <- "Number of comorbidities"
```

# HCPC
## ACM

```{r data-acm, echo=F}
data_acm <- data2[, c(1:9,11:235)]
data_acm[, c(1,3)] <- lapply(data_acm[, c(1,3)], as.character)
data_acm[, c(1,3)] <- lapply(data_acm[, c(1,3)], as.numeric)
data_acm[, c(2,4:234)] <- lapply(data_acm[, c(2,4:234)], as.factor)
```

```{r mca, echo=F, fig.width=15}
res.mca <- MCA(X = data_acm, quanti.sup = c(1,3) , quali.sup = c(2,4:33), graph = F)
fviz_screeplot(res.mca, addlabels =T)
res.mca$eig[1:5,] %>%
  kbl() %>%
  kable_minimal(full_width=F)
res.mca <- MCA(X = data_acm, quanti.sup = c(1,3) , quali.sup = c(2,4:33), graph = F, ncp=300)
```

## CAH

```{r hcpc, message=F, echo=F}
res_cah_ward <- HCPC(res.mca, max=10, consol = 0, graph=F, nb.clust = -1, method = "ward")
res_kmeans_ward <- HCPC(res.mca, max=10, consol = 1, graph=F, nb.clust = -1, method = "ward")

res_cah_complete <- HCPC(res.mca, max=10, consol = 0, graph=F, nb.clust = -1, method = "complete")
res_kmeans_complete <- HCPC(res.mca, max=10, consol = 1, graph=F, nb.clust = -1, method = "complete")
  
res_cah_average <- HCPC(res.mca, max=10, consol = 0, graph=F, nb.clust = -1, method = "average")
res_kmeans_average <- HCPC(res.mca, max=10, consol = 1, graph=F, nb.clust = -1, method = "average")

table(res_kmeans_ward$data.clust$clust)
table(res_kmeans_complete$data.clust$clust)
table(res_kmeans_average$data.clust$clust)

adj.rand.index(res_kmeans_ward$data.clust$clust, res_kmeans_complete$data.clust$clust)
adj.rand.index(res_kmeans_complete$data.clust$clust, res_kmeans_average$data.clust$clust)

plot(res_kmeans_ward, choice = "tree")
```

## Description of clusters

```{r, rpz-age-clusters, echo=F, fig.cap="Representation of the age of the participants according to the classes obtained."}
violin_age <- res_kmeans_ward$data.clust %>% 
  ggplot() +
  geom_violin(trim = FALSE, adjust=0.8, aes(x = clust, y = age, fill = clust), show.legend = F) +
  geom_boxplot(aes(y = age, x = clust), width = 0.1, show.legend = F) +
  labs(fill = "Breast cancer") +
  scale_fill_manual(values =c('#ada7c9', "#56BCC3", "#E77D71", "#99d98c")) +
  stat_summary(aes(x = clust, y = age, fill = clust), fun = mean, geom = "point", 
               shape = 4, size = 5, col = "black",show.legend = F) +
  scale_y_continuous(limits=c(0, 100)) +
  labs(title = "", x = "Class", y = "Age") + theme_classic() 
violin_age
```

```{r descriptif-hcpc, echo=F}
data2$cluster_hcpc <- as.factor(res_kmeans_ward$data.clust$clust)
table1(~ age_cut_4 + age + imc_category + imc + marital_status + education  + current_work2 + 
         current_sociopro + residence_location_bis + region +
         nb_child_house  + bc_status + bc_status_bis + stage1 +
         breast_surgery + breast_chemo + breast_radio + breast_hormono + breast_immuno +
         breast_target + comor_heart + comor_neuro + comor_endo + comor_respi + comor_infla + comor_immun +
         comor_muscle + comor_depression + comor_locomotion + comor_other_cancer  +comor_nb+ activity + 
         pref_info_pa +
         pref_info_pa_who_famdoc + pref_info_pa_who_onco + pref_info_pa_who_nurse + 
         pref_info_pa_who_hospcoach +
         pref_info_pa_who_gymcoach + pref_info_pa_who_patient + pref_info_pa_who_persocoach +
         pref_info_pa_who_physio + pref_info_pa_who_nopref + pref_info_pa_how_phone +
         pref_info_pa_how_sms + pref_info_pa_how_app + pref_info_pa_how_mail + pref_info_pa_how_web +
         pref_info_pa_how_dvd + pref_info_pa_how_video + pref_info_pa_how_leaflet +
         pref_info_pa_how_online + pref_info_pa_how_podcast + pref_info_pa_how_facetoface +
         pref_info_pa_how_group + pref_pa_interest + pref_pa_able + pref_pa_type_walking +
         pref_pa_type_swimming + pref_pa_type_gym + pref_pa_type_biking + pref_pa_type_dance +
         pref_pa_type_running + pref_pa_type_strengthening + pref_pa_type_yoga + pref_pa_type_pilates + 
         pref_pa_type_fitness + pref_pa_type_racket + pref_pa_type_team + pref_pa_where_outside + 
         pref_pa_where_home + pref_pa_where_work + pref_pa_where_club + 
         pref_pa_where_hospital + pref_pa_where_nopref + pref_pa_how_alone + pref_pa_how_peer + 
         pref_pa_how_patient + pref_pa_how_group + pref_pa_how_nopref + pref_pa_sup + pref_pa_intensity +
         pref_pa_orga + pref_pa_recur + pref_pa_moment + pref_pa_week + pref_pa_nbday +
         pref_pa_duration + pref_pa_strategy_gp_online + pref_pa_strategy_indiv_online + 
         pref_pa_strategy_online +
         pref_pa_strategy_phone + pref_pa_strategy_sms + pref_pa_strategy_mail + 
         pref_pa_strategy_leaflet + pref_pa_strategy_video + pref_pa_strategy_socialnet +
         pref_pa_strategy_tracker + pref_pa_strategy_app + pref_pa_strategy_notebook + 
         pref_pa_strategy_web + pref_pa_strategy_share_entourage + pref_pa_strategy_share_doctor +
         pref_pa_strategy_doc + pref_pa_strategy_usb + pref_pa_strategy_dvd +
         techno_socialnetwork_fb + techno_socialnetwork_instagram +
         techno_socialnetwork_linkedin + techno_socialnetwork_twitter + techno_socialnetwork_no +
         techno_app_adidas + techno_app_fitbit + techno_app_fizzup + techno_app_garmin +
         techno_app_nike + techno_app_runtastic + techno_app_strava +
         techno_app_withings + techno_app_xiaomi + techno_app_healthapp + techno_app_no +
         techno_tracker_apple + techno_tracker_fitbit + techno_tracker_galaxy +
         techno_tracker_garmin + techno_tracker_withings + 
         techno_tracker_xiaomi + techno_tracker_podo + techno_tracker_smartphone_podo +
         techno_tracker_no + techno_tracker_fq + techno_prog_tracker +
         techno_prog_tracker_no_use + techno_prog_tracker_no_info +
         techno_prog_tracker_no_price + techno_prog_tracker_no_security +
         techno_prog_tracker_no_dependancy + techno_prog_tracker_no_reliability +
         techno_prog_tracker_no_wrist + techno_prog_tracker_no_allergy +
         techno_prog_tracker_no_opportunity + techno_prog_tracker_no_userfriendly +
         techno_prog_tracker_no_malfunction + techno_prog_tracker_no_alone +
         techno_prog_tracker_no_active + techno_prog_tracker_no_interest +
         techno_prog_tracker_no_unable + techno_prog_tracker_no_tmtime +
         techno_prog_tracker_fun_step + techno_prog_tracker_fun_distance +
         techno_prog_tracker_fun_calorie + techno_prog_tracker_fun_nbfloor +
         techno_prog_tracker_fun_level + techno_prog_tracker_fun_hr +
         techno_prog_tracker_fun_sitting + techno_prog_tracker_fun_standing +
         techno_prog_tracker_fun_intensity + techno_prog_tracker_fun_type +
         techno_prog_tracker_fun_sleep +
         techno_prog_tracker_sha + techno_prog_app +
         techno_prog_app_no_use + techno_prog_app_no_info +
         techno_prog_app_no_security + techno_prog_app_no_dependency + 
         techno_prog_app_no_opportunity + techno_prog_app_no_userfriendly +
         techno_prog_app_no_malfunction + techno_prog_app_no_alone +
         techno_prog_app_no_active + techno_prog_app_no_interest +
         techno_prog_app_no_unable + techno_prog_app_no_tmtime  +
         techno_prog_web + techno_prog_web_no_use +
         techno_prog_web_no_info + techno_prog_web_no_security +
         techno_prog_web_no_dependency + techno_prog_web_no_opportunity +
         techno_prog_web_no_userfriendly + techno_prog_web_no_malfunction +
         techno_prog_web_no_alone + techno_prog_web_no_active +
         techno_prog_web_no_interest + techno_prog_web_no_unable +
         barrier_pa_fatigue + barrier_pa_weather +
         barrier_pa_pain + barrier_pa_partner +
         barrier_pa_schedule + barrier_pa_pleasure +
         barrier_pa_structure + barrier_pa_look +
         barrier_pa_interest + barrier_pa_family +
         barrier_pa_ignorance + barrier_pa_price +
         barrier_pa_injury + barrier_pa_social +
         barrier_pa_motivation + barrier_pa_sequelae +
         barrier_pa_transport + barrier_pa_organisation +
         barrier_pa_work + barrier_pa_unable +
         barrier_pa_insecurity + barrier_pa_priority +
         facilitator_pa_control + facilitator_pa_doctor +
         facilitator_pa_capacity + facilitator_pa_symptom +
         facilitator_pa_goal + facilitator_pa_qol +
         facilitator_pa_friend + facilitator_pa_sleep +
         facilitator_pa_structure + facilitator_pa_fatigue +
         facilitator_pa_group + facilitator_pa_weight +
         facilitator_pa_security + facilitator_pa_feeling +
         facilitator_pa_supervision + facilitator_pa_proud +
         facilitator_pa_immunity + facilitator_pa_pleasure +
         facilitator_pa_planning + facilitator_pa_energy| cluster_hcpc, 
       data = data2, droplevels=F,overall = F)
```

```{r barrier, fig.height=20, fig.width=10, echo=F}
data2$cluster_hcpc <- factor(data2$cluster_hcpc, levels = c(1:3),
                             labels=c("Classe 1", "Classe 2", "Classe 3"))
data_barrier <- data2[, 192:213]
item_all <- data_barrier
names(item_all) <- c(barrier_pa_fatigue= "02-Fatigue",
                         barrier_pa_weather = "04-Bad weather to practice",
                         barrier_pa_pain = "14-Severe pain",
                         barrier_pa_partner = "07-No partner to practice",
                         barrier_pa_schedule = "03-Schedule",
                         barrier_pa_pleasure = "12-Lack of pleasure",
                         barrier_pa_structure = "13-No structure around",
                         barrier_pa_look = "15-Fear of view of others", 
                         barrier_pa_interest = "19-Lack of interest",
                         barrier_pa_family = "08-Family commitments",
                         barrier_pa_ignorance = "10-Ignorance of practice",
                         barrier_pa_price = "11-Price",
                         barrier_pa_injury = "17-Fear of injury",
                         barrier_pa_social = "16-Prefer see friends",
                         barrier_pa_motivation = "01-Lack of motivation",
                         barrier_pa_sequelae = "22-Significant side effects",
                         barrier_pa_transport = "21-No transport",
                         barrier_pa_organisation = "05-Lack of organisation",
                         barrier_pa_work = "06-Work obligations",
                         barrier_pa_unable = "18-Unable",
                         barrier_pa_insecurity = "20-Fear of insecurity",
                         barrier_pa_priority = "09-Not my priority")
                         
l29g <- likert(item=item_all, grouping=data2$cluster_hcpc)
l29gs <- likert(summary = l29g$results[, 2:7], grouping = l29g$results[,1])
aa <- plot(l29gs, text.size=2, col=c('#a44a3f', '#f19c79','#f6f4d2', '#cbdfbd', '#95d5b2')) +
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(legend.position="right") 
aa
```

```{r faci, echo=F, fig.height=22, fig.cap="Agreement for physical activity barriers (in % on the Likert scale)."}
data_facilitator <- data2[, c( 214:235)]
item_all <- data_facilitator
names(item_all) <- c(facilitator_pa_control = "04-Health control",
                         facilitator_pa_doctor = "21-Doctor recommandation",
                         facilitator_pa_capacity = "02-Improve capacity",
                         facilitator_pa_etime = "15-Time to devote",
                         facilitator_pa_symptom = "22-Improve symptom",
                         facilitator_pa_goal = "12-Set a goal",
                         facilitator_pa_qol = "03-Improve quality of live",
                         facilitator_pa_friend = "17-Meet friends",
                         facilitator_pa_sleep = "11-Improve sleep",
                         facilitator_pa_structure = "20-Adapted structure",
                         facilitator_pa_fatigue = "16-Decrease fatigue",
                         facilitator_pa_group = "18-Group encouragement",
                         facilitator_pa_weight = "08-Weight control",
                         facilitator_pa_security = "10-Secure environment",
                         facilitator_pa_feeling = "01-Better in his body",
                         facilitator_pa_supervision = "19-Supervision by a professional",
                         facilitator_pa_proud = "07-Proud of oneself",
                         facilitator_pa_immunity = "09-Stimulate my immune system",
                         facilitator_pa_pleasure = "05-Feel pleasure ",
                         facilitator_pa_competent = "14-Feel competent",
                         facilitator_pa_planning = "13-Organizing my schedule",
                         facilitator_pa_energy = "06-Regain energy")

l29g <- likert(item=item_all, grouping=data2$cluster_hcpc)
l29gs <- likert(summary = l29g$results[, 2:7], grouping = l29g$results[,1])
aaa <- plot(l29gs, text.size=2, col=c('#a44a3f', '#f19c79','#f6f4d2', '#cbdfbd', '#95d5b2')) +
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(legend.position="right")
aaa
```

## Régréssion logisitique multinomiale 

```{r model-log, echo=F, message=F, warning=F}
data2$cluster_hcpc <- relevel(data2$cluster_hcpc, ref = "Classe 2")
data2$age_cut_4 <- relevel(data2$age_cut_4, ref = "30-50")
data2$imc_category <- relevel(data2$imc_category, ref = "Normal")
data2$activity <- relevel(data2$activity, ref = "Active")
data2$marital_status <- relevel(data2$marital_status, ref = "Single")
data2$education <- relevel(data2$education, ref = "BAC")
data2$current_sociopro <- relevel(data2$current_sociopro, ref = "Employed")

# univarie
mod1 <- multinom(cluster_hcpc ~ age_cut_4, data=data2, trace=F)
odds.ratio(mod1)
mod2 <- multinom(cluster_hcpc ~ imc_category, data=data2, trace=F)
odds.ratio(mod2)
mod3 <- multinom(cluster_hcpc ~ marital_status, data=data2, trace=F)
odds.ratio(mod3)
mod4 <- multinom(cluster_hcpc ~ education, data=data2, trace=F)
odds.ratio(mod4)
mod5 <- multinom(cluster_hcpc ~ bc_status_bis, data=data2, trace=F)
odds.ratio(mod5)
mod6 <- multinom(cluster_hcpc ~ activity, data=data2, trace=F)
odds.ratio(mod6)

# stepwise approach
fullmod <- multinom(cluster_hcpc ~ age_cut_4  + imc_category + marital_status + bc_status_bis + activity, data=data2, trace=F)
nothing <- multinom(cluster_hcpc ~ 1, data=data2, trace=F)
bothways <- step(nothing, list(lower=formula(nothing),upper=formula(fullmod)), direction="both",trace=0)
ggcoef_model(bothways, exponentiate = T) 
```
